## Preprocessing

In [3]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.14.0-cp310-cp310-macosx_12_0_arm64.whl (2.1 kB)
Collecting tensorflow-macos==2.14.0
  Downloading tensorflow_macos-2.14.0-cp310-cp310-macosx_12_0_arm64.whl (199.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 MB 9.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (1.14.1)
Requirement already satisfied: numpy>=1.23.5 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (1.24.3)
Requirement already satisfied: setuptools in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (67.8.0)
Collecting tensorflow-estimator<2.15,>=2.14.0
  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl (440 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 13.0 MB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (4.5.0)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1
  Downloading gast-0.5.4-py3-none-any.whl (19 kB)
Requirement already satisfied: h5py>=2.9.0 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (3.7.0)
Requirement already satisfied: six>=1.12.0 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (1.16.0)
Collecting absl-py>=1.0.0
  Using cached absl_py-2.0.0-py3-none-any.whl (130 kB)
Collecting tensorboard<2.15,>=2.14
  Downloading tensorboard-2.14.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.6 MB/s eta 0:00:0000:0100:01
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.34.0-cp310-cp310-macosx_12_0_arm64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 14.4 MB/s eta 0:00:0000:0100:01
Collecting keras<2.15,>=2.14.0
  Downloading keras-2.14.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 14.4 MB/s eta 0:00:0000:0100:01
Collecting libclang>=13.0.0
  Downloading libclang-16.0.6-py2.py3-none-macosx_11_0_arm64.whl (20.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 16.3 MB/s eta 0:00:0000:0100:01
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.59.0-cp310-cp310-macosx_12_0_universal2.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 17.2 MB/s eta 0:00:0000:0100:01
Collecting termcolor>=1.1.0
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 4.9 MB/s eta 0:00:00
Collecting ml-dtypes==0.2.0
  Downloading ml_dtypes-0.2.0-cp310-cp310-macosx_10_9_universal2.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.1 MB/s eta 0:00:00a 0:00:01
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3
  Downloading protobuf-4.24.4-cp37-abi3-macosx_10_9_universal2.whl (409 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.4/409.4 kB 19.6 MB/s eta 0:00:00
Requirement already satisfied: packaging in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorflow-macos==2.14.0->tensorflow) (23.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow-macos==2.14.0->tensorflow) (0.38.4)
Collecting google-auth-oauthlib<1.1,>=0.5
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.23.3-py2.py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.3/182.3 kB 14.4 MB/s eta 0:00:00
Collecting tensorboard-data-server<0.8.0,>=0.7.0
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Requirement already satisfied: markdown>=2.6.8 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (3.4.1)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (2.2.3)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (2.29.0)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (0.2.8)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: idna<4,>=2.5 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (2023.7.22)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (2.0.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/iman/anaconda3/envs/dev/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-macos==2.14.0->tensorflow) (0.4.8)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 10.2 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, opt-einsum, oauthlib, ml-dtypes, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-macos, tensorflow
Successfully installed absl-py-2.0.0 astunparse-1.6.3 cachetools-5.3.2 flatbuffers-23.5.26 gast-0.5.4 google-auth-2.23.3 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.59.0 keras-2.14.0 libclang-16.0.6 ml-dtypes-0.2.0 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.24.4 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.14.1 tensorboard-data-server-0.7.2 tensorflow-2.14.0 tensorflow-estimator-2.14.0 tensorflow-io-gcs-filesystem-0.34.0 tensorflow-macos-2.14.0 termcolor-2.3.0

Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns = ['EIN', 'NAME'], inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [6]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df ['APPLICATION_TYPE'].value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_count[app_count<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
classifications_count = application_df['CLASSIFICATION'].value_counts()
classifications_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classifications_count[classifications_count<1000].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies = pd.get_dummies(application_df)
app_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = app_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = app_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]
hidden_node_1 =80
hidden_node_2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node_1, activation='relu', input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node_2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 668us/step - loss: 0.5725 - accuracy: 0.7186
Epoch 2/100
804/804 [==============================] - 1s 648us/step - loss: 0.5554 - accuracy: 0.7277
Epoch 3/100
804/804 [==============================] - 1s 643us/step - loss: 0.5525 - accuracy: 0.7291
Epoch 4/100
804/804 [==============================] - 1s 641us/step - loss: 0.5502 - accuracy: 0.7307
Epoch 5/100
804/804 [==============================] - 1s 642us/step - loss: 0.5491 - accuracy: 0.7314
Epoch 6/100
804/804 [==============================] - 1s 644us/step - loss: 0.5479 - accuracy: 0.7321
Epoch 7/100
804/804 [==============================] - 1s 645us/step - loss: 0.5476 - accuracy: 0.7336
Epoch 8/100
804/804 [==============================] - 1s 643us/step - loss: 0.5471 - accuracy: 0.7337
Epoch 9/100
804/804 [==============================] - 1s 644us/step - loss: 0.5462 - accuracy: 0.7336
Epoch 10/100
804/804 [==============================] - 1s 643us/step - loss: 0.5457 - accuracy: 0.7336
Epoch 11/100
804/804 [==============================] - 1s 642us/step - loss: 0.5455 - accuracy: 0.7341
Epoch 12/100
804/804 [==============================] - 1s 643us/step - loss: 0.5453 - accuracy: 0.7338
Epoch 13/100
804/804 [==============================] - 1s 644us/step - loss: 0.5446 - accuracy: 0.7334
Epoch 14/100
804/804 [==============================] - 1s 641us/step - loss: 0.5442 - accuracy: 0.7339
Epoch 15/100
804/804 [==============================] - 1s 641us/step - loss: 0.5438 - accuracy: 0.7347
Epoch 16/100
804/804 [==============================] - 1s 642us/step - loss: 0.5434 - accuracy: 0.7352
Epoch 17/100
804/804 [==============================] - 1s 643us/step - loss: 0.5437 - accuracy: 0.7338
Epoch 18/100
804/804 [==============================] - 1s 644us/step - loss: 0.5434 - accuracy: 0.7359
Epoch 19/100
804/804 [==============================] - 1s 662us/step - loss: 0.5430 - accuracy: 0.7351
Epoch 20/100
804/804 [==============================] - 1s 652us/step - loss: 0.5422 - accuracy: 0.7357
Epoch 21/100
804/804 [==============================] - 1s 670us/step - loss: 0.5419 - accuracy: 0.7356
Epoch 22/100
804/804 [==============================] - 1s 702us/step - loss: 0.5419 - accuracy: 0.7355
Epoch 23/100
804/804 [==============================] - 1s 678us/step - loss: 0.5415 - accuracy: 0.7367
Epoch 24/100
804/804 [==============================] - 1s 643us/step - loss: 0.5416 - accuracy: 0.7355
Epoch 25/100
804/804 [==============================] - 1s 645us/step - loss: 0.5417 - accuracy: 0.7367
Epoch 26/100
804/804 [==============================] - 1s 644us/step - loss: 0.5409 - accuracy: 0.7363
Epoch 27/100
804/804 [==============================] - 1s 644us/step - loss: 0.5407 - accuracy: 0.7364
Epoch 28/100
804/804 [==============================] - 1s 644us/step - loss: 0.5408 - accuracy: 0.7370
Epoch 29/100
804/804 [==============================] - 1s 644us/step - loss: 0.5405 - accuracy: 0.7358
Epoch 30/100
804/804 [==============================] - 1s 645us/step - loss: 0.5397 - accuracy: 0.7376
Epoch 31/100
804/804 [==============================] - 1s 704us/step - loss: 0.5400 - accuracy: 0.7369
Epoch 32/100
804/804 [==============================] - 1s 735us/step - loss: 0.5404 - accuracy: 0.7364
Epoch 33/100
804/804 [==============================] - 1s 719us/step - loss: 0.5392 - accuracy: 0.7375
Epoch 34/100
804/804 [==============================] - 1s 687us/step - loss: 0.5393 - accuracy: 0.7364
Epoch 35/100
804/804 [==============================] - 1s 681us/step - loss: 0.5390 - accuracy: 0.7366
Epoch 36/100
804/804 [==============================] - 1s 705us/step - loss: 0.5393 - accuracy: 0.7379
Epoch 37/100
804/804 [==============================] - 1s 701us/step - loss: 0.5388 - accuracy: 0.7369
Epoch 38/100
804/804 [==============================] - 1s 668us/step - loss: 0.5387 - accuracy: 0.7378
Epoch 39/100
804/804 [==============================] - 1s 677us/step - loss: 0.5390 - accuracy: 0.7372
Epoch 40/100
804/804 [==============================] - 1s 707us/step - loss: 0.5387 - accuracy: 0.7372
Epoch 41/100
804/804 [==============================] - 1s 755us/step - loss: 0.5382 - accuracy: 0.7376
Epoch 42/100
804/804 [==============================] - 1s 692us/step - loss: 0.5381 - accuracy: 0.7378
Epoch 43/100
804/804 [==============================] - 1s 722us/step - loss: 0.5381 - accuracy: 0.7385
Epoch 44/100
804/804 [==============================] - 1s 703us/step - loss: 0.5375 - accuracy: 0.7377
Epoch 45/100
804/804 [==============================] - 1s 691us/step - loss: 0.5377 - accuracy: 0.7391
Epoch 46/100
804/804 [==============================] - 1s 658us/step - loss: 0.5377 - accuracy: 0.7388
Epoch 47/100
804/804 [==============================] - 1s 663us/step - loss: 0.5373 - accuracy: 0.7395
Epoch 48/100
804/804 [==============================] - 1s 675us/step - loss: 0.5371 - accuracy: 0.7381
Epoch 49/100
804/804 [==============================] - 1s 727us/step - loss: 0.5374 - accuracy: 0.7376
Epoch 50/100
804/804 [==============================] - 1s 710us/step - loss: 0.5371 - accuracy: 0.7383
Epoch 51/100
804/804 [==============================] - 1s 707us/step - loss: 0.5369 - accuracy: 0.7385
Epoch 52/100
804/804 [==============================] - 1s 665us/step - loss: 0.5366 - accuracy: 0.7381
Epoch 53/100
804/804 [==============================] - 1s 671us/step - loss: 0.5368 - accuracy: 0.7393
Epoch 54/100
804/804 [==============================] - 1s 648us/step - loss: 0.5365 - accuracy: 0.7394
Epoch 55/100
804/804 [==============================] - 1s 645us/step - loss: 0.5367 - accuracy: 0.7369
Epoch 56/100
804/804 [==============================] - 1s 649us/step - loss: 0.5365 - accuracy: 0.7397
Epoch 57/100
804/804 [==============================] - 1s 650us/step - loss: 0.5367 - accuracy: 0.7392
Epoch 58/100
804/804 [==============================] - 1s 661us/step - loss: 0.5362 - accuracy: 0.7386
Epoch 59/100
804/804 [==============================] - 1s 684us/step - loss: 0.5362 - accuracy: 0.7398
Epoch 60/100
804/804 [==============================] - 1s 673us/step - loss: 0.5359 - accuracy: 0.7393
Epoch 61/100
804/804 [==============================] - 1s 655us/step - loss: 0.5362 - accuracy: 0.7392
Epoch 62/100
804/804 [==============================] - 1s 672us/step - loss: 0.5358 - accuracy: 0.7400
Epoch 63/100
804/804 [==============================] - 1s 653us/step - loss: 0.5356 - accuracy: 0.7401
Epoch 64/100
804/804 [==============================] - 1s 663us/step - loss: 0.5356 - accuracy: 0.7402
Epoch 65/100
804/804 [==============================] - 1s 656us/step - loss: 0.5362 - accuracy: 0.7391
Epoch 66/100
804/804 [==============================] - 1s 678us/step - loss: 0.5355 - accuracy: 0.7396
Epoch 67/100
804/804 [==============================] - 1s 671us/step - loss: 0.5357 - accuracy: 0.7395
Epoch 68/100
804/804 [==============================] - 1s 654us/step - loss: 0.5359 - accuracy: 0.7387
Epoch 69/100
804/804 [==============================] - 1s 664us/step - loss: 0.5349 - accuracy: 0.7392
Epoch 70/100
804/804 [==============================] - 1s 671us/step - loss: 0.5353 - accuracy: 0.7385
Epoch 71/100
804/804 [==============================] - 1s 686us/step - loss: 0.5353 - accuracy: 0.7391
Epoch 72/100
804/804 [==============================] - 1s 660us/step - loss: 0.5354 - accuracy: 0.7389
Epoch 73/100
804/804 [==============================] - 1s 668us/step - loss: 0.5348 - accuracy: 0.7389
Epoch 74/100
804/804 [==============================] - 1s 661us/step - loss: 0.5347 - accuracy: 0.7399
Epoch 75/100
804/804 [==============================] - 1s 672us/step - loss: 0.5348 - accuracy: 0.7403
Epoch 76/100
804/804 [==============================] - 1s 658us/step - loss: 0.5347 - accuracy: 0.7387
Epoch 77/100
804/804 [==============================] - 1s 684us/step - loss: 0.5350 - accuracy: 0.7399
Epoch 78/100
804/804 [==============================] - 1s 675us/step - loss: 0.5352 - accuracy: 0.7390
Epoch 79/100

804/804 [==============================] - 1s 654us/step - loss: 0.5351 - accuracy: 0.7396
Epoch 80/100
804/804 [==============================] - 1s 640us/step - loss: 0.5347 - accuracy: 0.7397
Epoch 81/100
804/804 [==============================] - 1s 640us/step - loss: 0.5345 - accuracy: 0.7398
Epoch 82/100
804/804 [==============================] - 1s 655us/step - loss: 0.5343 - accuracy: 0.7405
Epoch 83/100
804/804 [==============================] - 1s 658us/step - loss: 0.5348 - accuracy: 0.7399
Epoch 84/100
804/804 [==============================] - 1s 657us/step - loss: 0.5341 - accuracy: 0.7402
Epoch 85/100
804/804 [==============================] - 1s 644us/step - loss: 0.5347 - accuracy: 0.7393
Epoch 86/100
804/804 [==============================] - 1s 665us/step - loss: 0.5340 - accuracy: 0.7399
Epoch 87/100
804/804 [==============================] - 1s 665us/step - loss: 0.5342 - accuracy: 0.7403
Epoch 88/100
804/804 [==============================] - 1s 661us/step - loss: 0.5341 - accuracy: 0.7400
Epoch 89/100
804/804 [==============================] - 1s 658us/step - loss: 0.5345 - accuracy: 0.7397
Epoch 90/100
804/804 [==============================] - 1s 669us/step - loss: 0.5342 - accuracy: 0.7398
Epoch 91/100
804/804 [==============================] - 1s 668us/step - loss: 0.5339 - accuracy: 0.7404
Epoch 92/100
804/804 [==============================] - 1s 673us/step - loss: 0.5343 - accuracy: 0.7397
Epoch 93/100
804/804 [==============================] - 1s 654us/step - loss: 0.5340 - accuracy: 0.7398
Epoch 94/100
804/804 [==============================] - 1s 744us/step - loss: 0.5335 - accuracy: 0.7410
Epoch 95/100
804/804 [==============================] - 1s 655us/step - loss: 0.5341 - accuracy: 0.7403
Epoch 96/100
804/804 [==============================] - 1s 643us/step - loss: 0.5339 - accuracy: 0.7399
Epoch 97/100
804/804 [==============================] - 1s 643us/step - loss: 0.5335 - accuracy: 0.7408
Epoch 98/100
804/804 [==============================] - 1s 643us/step - loss: 0.5337 - accuracy: 0.7406
Epoch 99/100
804/804 [==============================] - 1s 641us/step - loss: 0.5335 - accuracy: 0.7404
Epoch 100/100
804/804 [==============================] - 1s 643us/step - loss: 0.5337 - accuracy: 0.7407

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5655 - accuracy: 0.7280 - 189ms/epoch - 706us/step
Loss: 0.5655259490013123, Accuracy: 0.7280466556549072

In [21]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')